<h1>Félicitations!</h1>
<p>La réponse était "une soixantaine".</p>
<p><a href="index.php?i=1" class="btn btn-primary">Indice pour trouver le QR Code suivant</a></p>
<h3>Plus d'informations</h3>
<p>Nous avons la chance d'étudier dans une université placant les activités para-universitaires au coeur de la vie sur le campus. Il y a à ce jour plus de 60 cercles et associations reconnus par le Conseil d'Administration. Ceux-ci sont divisés en deux grandes catégories : les Cercles membres de l'Association des Cercles Etudiants d'une part, et les Cercles et associations membres de la Plateforme des Associations Socio-Culturelles. </p>
<p>Il existe beaucoup de types de Cercles et associations. Il existe par exemple les cercles facultaires (Cercle des Sciences, Cercle de Philosophie et Lettres, Cercle Polytecnique, ...), les cercles de section (Cercle Informatique, Cercle de Romanes, Cercle de Journalisme et Communication, ...), les cercles régionnaux (Cercles des Etudiants du Centre et Sympathisants, La Frontalière, ...), les associations politiques (Comac, Etudiants FGTB, Cercle des Etudiants Libéraux, ...), les assocations culturelles (OPAC, La Nocturne, ...) et encore bien d'autres.</p>
<p>Cette vie associative et culturelle est riche et anime nos campus tout au long de l'année, que ce soit par le biais de gros évènements touchant l'ensemble de la communauté estudiantine (6h Cuistax du Cercle Polytechnique, Beach Volley du Cercle Solvay, La Nocturne, ...) que par le biais d'évènements plus ciblés et d'importance plus variable (débats et actions politiques, projections de films, conférences, ...).</p>
<p>Ces associations offrent aussi des services divers et variés aux étudiants désireux d'en profiter : vente de syllabus et de notes, organisation de petits-déjeuners équitables, représentation étudiante à divers niveaux administratifs et académiques, ...</p>
<p>Mais la vie para-universitaire sur le campus ne s'arrête pas aux associations estudiantines : ULB Culture, ULB Sports et La Médiathèque jouent aussi de grands rôles dans leurs domaines respectifs. ULB Culture organise diverses expositions tout au long de l'année, ULB Sports propose une large gamme d'activités sportives accessibles avec la carte Sports, et la Médiathèque quand à elle, outre ses services de locations habituels, organise régulièrement des concerts.</p>
<p>Enfin, l'Université encourage ses étudiants à s'impliquer dans cette vie associative, que ce soit par le biais d'un investissement dans l'une des nombreuses structures déjà existantes ou par la création d'une nouvelle pouvant répondre à une demande encore non-rencontrée. Par exemple, un hackerspace (laboratoire d'informatique et d'électronique ouvert) a été créé l'an passé et rencontre un franc succès auprès d'étudiants en informatique et en polytech.</p>